# Generated by Django 5.0.4 on 2024-04-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_create_date_alter_course_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='l_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='m_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='x_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
